import { cookies } from 'next/headers'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/app/components/Navbar'
import { verifyAuth } from "./lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}) {
  const cookieStore = await cookies();   
  const token = cookieStore.get("authToken")?.value;
  const user = verifyAuth(token);
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <Navbar userRole={user?.userRole || null}/>
        {children}
      </body>
    </html>
  );
}
